"""add description to units

Revision ID: d652a2cd67fc
Revises: 1a6ef6a64f85
Create Date: 2026-08-18 09:40:21.365940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd652a2cd67fc'
down_revision: Union[str, Sequence[str], None] = '1a6ef6a64f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'description')
    # ### end Alembic commands ###
